"""Database models, connection engine, and read-only query runner."""

import datetime
from typing import Any, Dict, List, Optional
from sqlalchemy import (
    Column, Integer, String, Float, ForeignKey, DateTime, Text, Boolean, text
)
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy.orm import declarative_base, relationship as orm_relationship

from app.core.config import settings

Base = declarative_base()

# ---------------------------------------------------------------------------
# School ERP ORM Models
# ---------------------------------------------------------------------------

class Student(Base):
    __tablename__ = "students"

    id = Column(Integer, primary_key=True, index=True)
    first_name = Column(String(50), nullable=False)
    last_name = Column(String(50), nullable=False)
    email = Column(String(100), unique=True, nullable=False, index=True)
    grade_level = Column(String(20), nullable=False)
    status = Column(String(20), default="active")  # active, graduated, suspended

    guardians = orm_relationship("Guardian", back_populates="student")
    invoices = orm_relationship("FeeInvoice", back_populates="student")
    attendance_records = orm_relationship("Attendance", back_populates="student")


class Guardian(Base):
    __tablename__ = "guardians"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    name = Column(String(100), nullable=False)
    email = Column(String(100), nullable=False)
    phone = Column(String(30), nullable=True)
    relationship = Column(String(30), default="Parent")  # Mother, Father, Guardian

    student = orm_relationship("Student", back_populates="guardians")


class FeeInvoice(Base):
    __tablename__ = "fee_invoices"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    term = Column(String(50), nullable=False)  # e.g., "Fall 2026", "Spring 2026"
    total_amount = Column(Float, nullable=False)
    balance_due = Column(Float, nullable=False)
    due_date = Column(String(20), nullable=False)  # YYYY-MM-DD
    status = Column(String(20), default="unpaid")  # paid, partial, unpaid, overdue

    student = orm_relationship("Student", back_populates="invoices")
    payments = orm_relationship("Payment", back_populates="invoice")


class Payment(Base):
    __tablename__ = "payments"

    id = Column(Integer, primary_key=True, index=True)
    invoice_id = Column(Integer, ForeignKey("fee_invoices.id"), nullable=False)
    amount_paid = Column(Float, nullable=False)
    payment_date = Column(String(20), nullable=False)
    payment_method = Column(String(50), default="card")  # card, bank_transfer, cash

    invoice = orm_relationship("FeeInvoice", back_populates="payments")


class Attendance(Base):
    __tablename__ = "attendance"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    date = Column(String(20), nullable=False)  # YYYY-MM-DD
    status = Column(String(20), nullable=False)  # present, absent, tardy, excused

    student = orm_relationship("Student", back_populates="attendance_records")


class Course(Base):
    __tablename__ = "courses"

    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(20), unique=True, nullable=False)
    title = Column(String(100), nullable=False)
    department = Column(String(50), nullable=False)


class Enrollment(Base):
    __tablename__ = "enrollments"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    course_id = Column(Integer, ForeignKey("courses.id"), nullable=False)
    semester = Column(String(30), nullable=False)
    grade = Column(String(5), nullable=True)


class Assessment(Base):
    """Continuous assessment record (quizzes, midterms, projects, finals)."""
    __tablename__ = "assessments"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    course_id = Column(Integer, ForeignKey("courses.id"), nullable=False)
    assessment_name = Column(String(50), nullable=False)
    score = Column(Float, nullable=False)  # 0.0 to 100.0
    date = Column(String(20), nullable=False)  # YYYY-MM-DD


class StudentRiskAssessment(Base):
    """Daily predictive risk assessment generated by scikit-learn analytics."""
    __tablename__ = "student_risk_assessments"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    assessed_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))
    attendance_rate_30d = Column(Float, nullable=False)  # 0.0 to 1.0
    grade_drop_delta = Column(Float, nullable=False)  # baseline - recent (positive = drop)
    fee_delay_days = Column(Integer, default=0)
    balance_due = Column(Float, default=0.0)
    risk_score = Column(Float, nullable=False)  # calibrated probability 0.0 to 1.0
    risk_level = Column(String(20), nullable=False)  # Low, Medium, High
    top_risk_factors = Column(Text, nullable=True)  # JSON summary of risk drivers


class StudentIntervention(Base):
    """Guidance counselor briefing and teacher outreach generated by local LLM."""
    __tablename__ = "student_interventions"

    id = Column(Integer, primary_key=True, index=True)
    assessment_id = Column(Integer, ForeignKey("student_risk_assessments.id"), nullable=False)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    counselor_briefing = Column(Text, nullable=False)
    teacher_outreach = Column(Text, nullable=False)
    status = Column(String(30), default="pending_review")  # pending_review, actioned, dismissed
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))


class StudentDocument(Base):
    """Archived and classified student documents (TC, Medical, Birth Cert, etc.)."""
    __tablename__ = "student_documents"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=True)
    document_type = Column(String(50), nullable=False)
    file_name = Column(String(255), nullable=False)
    student_name_extracted = Column(String(100), nullable=True)
    dob_extracted = Column(String(30), nullable=True)
    issuing_authority = Column(String(150), nullable=True)
    document_date = Column(String(30), nullable=True)
    document_id_number = Column(String(100), nullable=True)
    confidence = Column(Float, default=0.95)
    extracted_metadata = Column(Text, nullable=True)
    status = Column(String(30), default="processed")
    uploaded_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))


class TeacherBehavioralNote(Base):
    """Observations recorded by classroom teachers regarding student behavior, participation, and habits."""
    __tablename__ = "teacher_behavioral_notes"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    term = Column(String(50), nullable=False)
    teacher_name = Column(String(100), nullable=False)
    category = Column(String(50), default="general")  # participation, collaboration, resilience, curiosity
    note_text = Column(Text, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))


class ReportCard(Base):
    """Automated, personalized narrative report card generated for end-of-term evaluations."""
    __tablename__ = "report_cards"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    term = Column(String(50), nullable=False)
    attendance_rate = Column(Float, nullable=False)
    average_score = Column(Float, nullable=False)
    narrative_summary = Column(Text, nullable=False)
    subject_breakdown = Column(Text, nullable=True)  # JSON
    growth_recommendations = Column(Text, nullable=True)
    status = Column(String(30), default="generated")  # generated, teacher_reviewed, published
    generated_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))


class AuditNotification(Base):
    """Audit log for notifications drafted or dispatched by AI or staff."""
    __tablename__ = "audit_notifications"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=False)
    message_body = Column(Text, nullable=False)
    channel = Column(String(30), default="email")
    status = Column(String(30), default="drafted")  # drafted, queued, sent, failed
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))


# ---------------------------------------------------------------------------
# Database Engine & Session Factory
# ---------------------------------------------------------------------------

engine = create_async_engine(
    settings.DATABASE_URL,
    echo=settings.DEBUG,
    future=True,
)

async_session = async_sessionmaker(
    engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


async def init_db():
    """Create all tables if they do not already exist."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def execute_safe_readonly_query(sql_string: str, params: Optional[Dict[str, Any]] = None) -> List[Dict[str, Any]]:
    """Execute a validated read-only SQL query with database-level safeguards."""
    params = params or {}
    async with async_session() as session:
        # SQLite database-level read-only safeguard:
        try:
            await session.execute(text("PRAGMA query_only = ON;"))
            result = await session.execute(text(sql_string), params)
            rows = result.mappings().fetchmany(settings.SQL_MAX_ROWS)
            return [dict(row) for row in rows]
        finally:
            await session.execute(text("PRAGMA query_only = OFF;"))


# ---------------------------------------------------------------------------
# Database Seeder (Demo Data for School ERP)
# ---------------------------------------------------------------------------

async def seed_database_if_empty():
    """Populate realistic sample students, invoices, and guardians."""
    async with async_session() as session:
        result = await session.execute(text("SELECT COUNT(*) FROM students;"))
        count = result.scalar()
        if count and count > 0:
            return  # Already seeded

        # Students
        students_data = [
            Student(id=1, first_name="Liam", last_name="Johnson", email="liam.j@school.edu", grade_level="Grade 10", status="active"),
            Student(id=2, first_name="Sophia", last_name="Martinez", email="sophia.m@school.edu", grade_level="Grade 11", status="active"),
            Student(id=3, first_name="Noah", last_name="Brown", email="noah.b@school.edu", grade_level="Grade 9", status="active"),
            Student(id=4, first_name="Emma", last_name="Davis", email="emma.d@school.edu", grade_level="Grade 12", status="active"),
            Student(id=5, first_name="Oliver", last_name="Wilson", email="oliver.w@school.edu", grade_level="Grade 10", status="active"),
        ]
        session.add_all(students_data)

        # Guardians
        guardians_data = [
            Guardian(student_id=1, name="Robert Johnson", email="robert.j@example.com", phone="+1-555-0101", relationship="Father"),
            Guardian(student_id=2, name="Elena Martinez", email="elena.m@example.com", phone="+1-555-0102", relationship="Mother"),
            Guardian(student_id=3, name="Marcus Brown", email="marcus.b@example.com", phone="+1-555-0103", relationship="Father"),
            Guardian(student_id=4, name="Sarah Davis", email="sarah.d@example.com", phone="+1-555-0104", relationship="Mother"),
            Guardian(student_id=5, name="James Wilson", email="james.w@example.com", phone="+1-555-0105", relationship="Father"),
        ]
        session.add_all(guardians_data)

        # Invoices (Liam and Noah haven't paid tuition!)
        invoices_data = [
            FeeInvoice(id=1, student_id=1, term="Fall 2026", total_amount=2500.0, balance_due=2500.0, due_date="2026-08-15", status="overdue"),
            FeeInvoice(id=2, student_id=2, term="Fall 2026", total_amount=2500.0, balance_due=0.0, due_date="2026-08-15", status="paid"),
            FeeInvoice(id=3, student_id=3, term="Fall 2026", total_amount=2500.0, balance_due=1500.0, due_date="2026-08-15", status="overdue"),
            FeeInvoice(id=4, student_id=4, term="Fall 2026", total_amount=2500.0, balance_due=0.0, due_date="2026-08-15", status="paid"),
            FeeInvoice(id=5, student_id=5, term="Fall 2026", total_amount=2500.0, balance_due=2500.0, due_date="2026-08-15", status="overdue"),
        ]
        session.add_all(invoices_data)

        # Payments
        payments_data = [
            Payment(invoice_id=2, amount_paid=2500.0, payment_date="2026-08-10", payment_method="card"),
            Payment(invoice_id=3, amount_paid=1000.0, payment_date="2026-08-12", payment_method="bank_transfer"),
            Payment(invoice_id=4, amount_paid=2500.0, payment_date="2026-08-01", payment_method="card"),
        ]
        session.add_all(payments_data)

        # Courses
        courses_data = [
            Course(id=1, code="MATH101", title="Algebra II", department="Mathematics"),
            Course(id=2, code="SCI201", title="Physics I", department="Science"),
            Course(id=3, code="ENG101", title="English Literature", department="Humanities"),
        ]
        session.add_all(courses_data)

        # Realistic Continuous Assessments (quizzes and midterms)
        assessments_data = [
            # Liam (Student 1) - steep academic decline
            Assessment(student_id=1, course_id=1, assessment_name="Quiz 1", score=88.0, date="2026-08-05"),
            Assessment(student_id=1, course_id=1, assessment_name="Quiz 2", score=70.0, date="2026-08-20"),
            Assessment(student_id=1, course_id=1, assessment_name="Midterm Exam", score=50.0, date="2026-09-05"),
            
            # Sophia (Student 2) - high consistent performance
            Assessment(student_id=2, course_id=1, assessment_name="Quiz 1", score=94.0, date="2026-08-05"),
            Assessment(student_id=2, course_id=1, assessment_name="Quiz 2", score=92.0, date="2026-08-20"),
            Assessment(student_id=2, course_id=1, assessment_name="Midterm Exam", score=95.0, date="2026-09-05"),
            
            # Noah (Student 3) - mild dip
            Assessment(student_id=3, course_id=1, assessment_name="Quiz 1", score=78.0, date="2026-08-05"),
            Assessment(student_id=3, course_id=1, assessment_name="Quiz 2", score=74.0, date="2026-08-20"),
            Assessment(student_id=3, course_id=1, assessment_name="Midterm Exam", score=70.0, date="2026-09-05"),
            
            # Emma (Student 4) - stable
            Assessment(student_id=4, course_id=1, assessment_name="Quiz 1", score=85.0, date="2026-08-05"),
            Assessment(student_id=4, course_id=1, assessment_name="Quiz 2", score=88.0, date="2026-08-20"),
            Assessment(student_id=4, course_id=1, assessment_name="Midterm Exam", score=87.0, date="2026-09-05"),
            
            # Oliver (Student 5) - severe decline
            Assessment(student_id=5, course_id=1, assessment_name="Quiz 1", score=76.0, date="2026-08-05"),
            Assessment(student_id=5, course_id=1, assessment_name="Quiz 2", score=60.0, date="2026-08-20"),
            Assessment(student_id=5, course_id=1, assessment_name="Midterm Exam", score=44.0, date="2026-09-05"),
        ]
        session.add_all(assessments_data)

        # 20-Day Attendance history for rolling averages
        attendance_data = []
        # Pattern: [Student 1: 60% present, Student 2: 95% present, Student 3: 80% present, Student 4: 100% present, Student 5: 50% present]
        student_presence = {
            1: [1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1],  # 12/20 (60%)
            2: [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],  # 19/20 (95%)
            3: [1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1],  # 16/20 (80%)
            4: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],  # 20/20 (100%)
            5: [1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],  # 10/20 (50%)
        }
        for s_id, records in student_presence.items():
            for day_idx, is_present in enumerate(records, start=1):
                day_str = f"2026-08-{day_idx:02d}"
                attendance_data.append(
                    Attendance(
                        student_id=s_id,
                        date=day_str,
                        status="present" if is_present else "absent",
                    )
                )
        session.add_all(attendance_data)

        # Teacher Behavioral Observations across the term
        behavioral_notes = [
            TeacherBehavioralNote(
                student_id=1,
                term="Fall 2026",
                teacher_name="Mrs. Sarah Jenkins",
                category="participation",
                note_text="Liam exhibits brilliant mathematical intuition during small-group lab activities, but his confidence drops when tackling multi-step algebraic proofs independently after missed lecture days.",
            ),
            TeacherBehavioralNote(
                student_id=1,
                term="Fall 2026",
                teacher_name="Mr. David Chen",
                category="curiosity",
                note_text="In Physics, Liam demonstrates authentic scientific curiosity regarding kinematics, though homework consistency has suffered recently.",
            ),
            TeacherBehavioralNote(
                student_id=2,
                term="Fall 2026",
                teacher_name="Mrs. Sarah Jenkins",
                category="collaboration",
                note_text="Sophia is an anchor in classroom discussions, frequently supporting peers through complex trigonometry proofs with remarkable patience and clarity.",
            ),
            TeacherBehavioralNote(
                student_id=3,
                term="Fall 2026",
                teacher_name="Mrs. Sarah Jenkins",
                category="resilience",
                note_text="Noah brings tremendous verbal energy and enthusiasm to group projects; establishing a structured daily review routine will help solidify his assessment retention.",
            ),
            TeacherBehavioralNote(
                student_id=4,
                term="Fall 2026",
                teacher_name="Mrs. Sarah Jenkins",
                category="diligence",
                note_text="Emma maintains steady academic focus, consistently submitting rigorous, immaculate homework assignments and demonstrating self-advocacy.",
            ),
            TeacherBehavioralNote(
                student_id=5,
                term="Fall 2026",
                teacher_name="Mrs. Sarah Jenkins",
                category="participation",
                note_text="Oliver shows artistic and spatial strengths; however, fragmented attendance has created significant comprehension gaps in geometry.",
            ),
        ]
        session.add_all(behavioral_notes)

        await session.commit()
